apiVersion: v1
data:
  vault-config.yml: |
    secrets:
      - type: gcp
        path: gcp/
        description: Google cloud secret backend
        configuration:
          config:
            - ttl: "30m"
              max_ttl: "60m"
          roleset:
            - name: tf_key
              secret_type: "service_account_key"
              project: "3134ed5d"
              bindings: |
                resource "//cloudresourcemanager.googleapis.com/projects/3134ed5d" {
                  roles = ["roles/editor"]
                }
            - name: tf_token
              secret_type: "access_token"
              token_scopes:
                - "https://www.googleapis.com/auth/cloud-platform"
              project: "3134ed5d"
              bindings: |
                resource "//cloudresourcemanager.googleapis.com/projects/3134ed5d" {
                  roles = ["roles/editor"]
                }
    policies:
      - name: gcp_admin_access
        rules: |
          path "gcp/token/tf_token"
          {
            capabilities = ["read"]
          }
          path "gcp/key/tf_key"
          {
            capabilities = ["read"]
          }
kind: ConfigMap
metadata:
  labels:
    app: vault-configurator
    vault_cr: vault
  name: vault-secrets-gcp
  namespace: default
